export const routeTitles = {
    Red: "Red Line",
    Blue: "Blue Line",
    Green: "Green Line",
    Orange: "Orange Line",
    Silver: "Silver Line",
    "CR-Fairmount": "Fairmount Line",
    "CR-Fitchburg": "Fitchburg Line",
    "CR-Worcester": "Framingham/Worcester Line",
    "CR-Franklin": "Franklin Line",
    "CR-Greenbush": "Greenbush Line",
    "CR-Haverhill": "Haverhill Line",
    "CR-Kingston": "Kingston/Plymouth Line",
    "CR-Lowell": "Lowell Line",
    "CR-Middleborough": "Middleborough/Lakeville Line",
    "CR-Needham": "Needham Line",
    "CR-Newburyport": "Newburyport/Rockport Line",
    "CR-Providence": "Providence/Stoughton Line",
    "CR-Foxboro": "Foxboro Event Service",
};
